---
# tasks file for ansible-role-kubectl-cfg

- name: "Configure kubectl"
  shell: |
         kubectl config set-cluster default-cluster \
         --server=http://"{{ hostvars[groups['k8s_masters'][0]]['inventory_hostname'] }}:{{ k8s_apiserver_port }}"

- name: "Set default context"
  shell: |
         kubectl config set-context default-context \
         --cluster=default-cluster --user=default-admin

- name: "Set default context"
  shell: |
         kubectl config use-context default-context