---
# tasks file for ansible-role-k8s-base
- name: "Include Debain / Redhat OS vars"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Install system requirements"
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ k8s_base_packages }}"

- include: "k8s-master.yml"
  when: inventory_hostname in groups['k8s_masters']

- include: "k8s-minion.yml"
  when: inventory_hostname in groups['k8s_minions']

